In [1]:
import censusgeocode
import pandas as pd
import numpy as np

In [2]:
crimes_df = pd.read_excel('2020crimes.xlsx')

In [3]:
crimes_df['Street\nType'] = crimes_df['Street\nType'].replace(np.nan, '', regex=True)

crimes_df = crimes_df.astype(str)

crimes_df

,Incident,Occurrence\nDate,Occurrence\nHour,NIBRS\nClass,NIBRSDescription,Offense\nCount,Beat,Premise,Block Range,StreetName,Street\nType,Suffix,City,ZIP Code
0,8220,2020-01-01,0,23G,Theft of motor vehicle parts or accessory,1,8C50,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,nan,HOUSTON,77078
1,18920,2020-01-01,0,13A,Aggravated Assault,1,17E30,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,nan,HOUSTON,77031
2,23020,2020-01-01,0,290,"Destruction, damage, vandalism",1,11H30,"Residence, Home (Includes Apartment)",8064,LENORE,,nan,HOUSTON,77017
3,24120,2020-01-01,0,13B,Simple assault,1,17E10,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,nan,HOUSTON,77081
4,27120,2020-01-01,0,290,"Destruction, damage, vandalism",1,14D30,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,nan,HOUSTON,77033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86909,72754920,2020-05-31,23,23G,Theft of motor vehicle parts or accessory,1,22B20,"Parking Lot, Garage",16501,CENTRAL GREEN,BLVD,nan,HOUSTON,77032
86910,72844720,2020-05-31,23,23F,Theft from motor vehicle,1,22B10,"Parking Lot, Garage",7815,WILLOW CHASE,BLVD,nan,HOUSTON,77070
86911,72913020,2020-05-31,23,13C,Intimidation,1,18F40,"Residence, Home (Includes Apartment)",9550,ELLA LEE,LN,nan,HOUSTON,77063
86912,72943020,2020-05-31,23,240,Motor vehicle theft,1,15E40,"Parking Lot, Garage",10000,FANNIN,ST,nan,HOUSTON,77045
86913,73067620,2020-05-31,23,23F,Theft from motor vehicle,1,4F20,"Parking Lot, Garage",10421,CLAY,RD,nan,HOUSTON,77041

In [4]:
crimes_df['address_number'] = crimes_df['Block Range'].apply(lambda x: x.split('-')[0])

In [5]:
crimes_df['address'] = crimes_df['address_number'] + ' ' + crimes_df['StreetName'] + ' ' + crimes_df['Street\nType']

crimes_df

,Incident,Occurrence\nDate,Occurrence\nHour,NIBRS\nClass,NIBRSDescription,Offense\nCount,Beat,Premise,Block Range,StreetName,Street\nType,Suffix,City,ZIP Code,address_number,address
0,8220,2020-01-01,0,23G,Theft of motor vehicle parts or accessory,1,8C50,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,nan,HOUSTON,77078,9311,9311 BELLA PINE CT
1,18920,2020-01-01,0,13A,Aggravated Assault,1,17E30,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,nan,HOUSTON,77031,8701,8701 GUSTINE LN
2,23020,2020-01-01,0,290,"Destruction, damage, vandalism",1,11H30,"Residence, Home (Includes Apartment)",8064,LENORE,,nan,HOUSTON,77017,8064,8064 LENORE
3,24120,2020-01-01,0,13B,Simple assault,1,17E10,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,nan,HOUSTON,77081,5930,5930 DASHWOOD DR
4,27120,2020-01-01,0,290,"Destruction, damage, vandalism",1,14D30,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,nan,HOUSTON,77033,5218,5218 KENILWOOD DR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86909,72754920,2020-05-31,23,23G,Theft of motor vehicle parts or accessory,1,22B20,"Parking Lot, Garage",16501,CENTRAL GREEN,BLVD,nan,HOUSTON,77032,16501,16501 CENTRAL GREEN BLVD
86910,72844720,2020-05-31,23,23F,Theft from motor vehicle,1,22B10,"Parking Lot, Garage",7815,WILLOW CHASE,BLVD,nan,HOUSTON,77070,7815,7815 WILLOW CHASE BLVD
86911,72913020,2020-05-31,23,13C,Intimidation,1,18F40,"Residence, Home (Includes Apartment)",9550,ELLA LEE,LN,nan,HOUSTON,77063,9550,9550 ELLA LEE LN
86912,72943020,2020-05-31,23,240,Motor vehicle theft,1,15E40,"Parking Lot, Garage",10000,FANNIN,ST,nan,HOUSTON,77045,10000,10000 FANNIN ST
86913,73067620,2020-05-31,23,23F,Theft from motor vehicle,1,4F20,"Parking Lot, Garage",10421,CLAY,RD,nan,HOUSTON,77041,10421,10421 CLAY RD

In [6]:
crimes_df['state'] = 'TX'

crimes_df

,Incident,Occurrence\nDate,Occurrence\nHour,NIBRS\nClass,NIBRSDescription,Offense\nCount,Beat,Premise,Block Range,StreetName,Street\nType,Suffix,City,ZIP Code,address_number,address,state
0,8220,2020-01-01,0,23G,Theft of motor vehicle parts or accessory,1,8C50,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,nan,HOUSTON,77078,9311,9311 BELLA PINE CT,TX
1,18920,2020-01-01,0,13A,Aggravated Assault,1,17E30,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,nan,HOUSTON,77031,8701,8701 GUSTINE LN,TX
2,23020,2020-01-01,0,290,"Destruction, damage, vandalism",1,11H30,"Residence, Home (Includes Apartment)",8064,LENORE,,nan,HOUSTON,77017,8064,8064 LENORE,TX
3,24120,2020-01-01,0,13B,Simple assault,1,17E10,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,nan,HOUSTON,77081,5930,5930 DASHWOOD DR,TX
4,27120,2020-01-01,0,290,"Destruction, damage, vandalism",1,14D30,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,nan,HOUSTON,77033,5218,5218 KENILWOOD DR,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86909,72754920,2020-05-31,23,23G,Theft of motor vehicle parts or accessory,1,22B20,"Parking Lot, Garage",16501,CENTRAL GREEN,BLVD,nan,HOUSTON,77032,16501,16501 CENTRAL GREEN BLVD,TX
86910,72844720,2020-05-31,23,23F,Theft from motor vehicle,1,22B10,"Parking Lot, Garage",7815,WILLOW CHASE,BLVD,nan,HOUSTON,77070,7815,7815 WILLOW CHASE BLVD,TX
86911,72913020,2020-05-31,23,13C,Intimidation,1,18F40,"Residence, Home (Includes Apartment)",9550,ELLA LEE,LN,nan,HOUSTON,77063,9550,9550 ELLA LEE LN,TX
86912,72943020,2020-05-31,23,240,Motor vehicle theft,1,15E40,"Parking Lot, Garage",10000,FANNIN,ST,nan,HOUSTON,77045,10000,10000 FANNIN ST,TX
86913,73067620,2020-05-31,23,23F,Theft from motor vehicle,1,4F20,"Parking Lot, Garage",10421,CLAY,RD,nan,HOUSTON,77041,10421,10421 CLAY RD,TX

In [7]:
crimes_df.rename(columns = {'Incident':'unique id', 'address':'street address', 'City':'city', 'ZIP Code':'zip code'}, inplace=True)

crimes_df.head()

,unique id,Occurrence\nDate,Occurrence\nHour,NIBRS\nClass,NIBRSDescription,Offense\nCount,Beat,Premise,Block Range,StreetName,Street\nType,Suffix,city,zip code,address_number,street address,state
0,8220,2020-01-01,0,23G,Theft of motor vehicle parts or accessory,1,8C50,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,nan,HOUSTON,77078,9311,9311 BELLA PINE CT,TX
1,18920,2020-01-01,0,13A,Aggravated Assault,1,17E30,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,nan,HOUSTON,77031,8701,8701 GUSTINE LN,TX
2,23020,2020-01-01,0,290,"Destruction, damage, vandalism",1,11H30,"Residence, Home (Includes Apartment)",8064,LENORE,,nan,HOUSTON,77017,8064,8064 LENORE,TX
3,24120,2020-01-01,0,13B,Simple assault,1,17E10,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,nan,HOUSTON,77081,5930,5930 DASHWOOD DR,TX
4,27120,2020-01-01,0,290,"Destruction, damage, vandalism",1,14D30,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,nan,HOUSTON,77033,5218,5218 KENILWOOD DR,TX

In [8]:
geo_df = crimes_df[['street address', 'city', 'zip code', 'state']]

geo_df

                 street address     city zip code state
0            9311 BELLA PINE CT  HOUSTON    77078    TX
1               8701 GUSTINE LN  HOUSTON    77031    TX
2                  8064 LENORE   HOUSTON    77017    TX
3              5930 DASHWOOD DR  HOUSTON    77081    TX
4             5218 KENILWOOD DR  HOUSTON    77033    TX
...                         ...      ...      ...   ...
86909  16501 CENTRAL GREEN BLVD  HOUSTON    77032    TX
86910    7815 WILLOW CHASE BLVD  HOUSTON    77070    TX
86911          9550 ELLA LEE LN  HOUSTON    77063    TX
86912           10000 FANNIN ST  HOUSTON    77045    TX
86913             10421 CLAY RD  HOUSTON    77041    TX

[86914 rows x 4 columns]

In [9]:
import numpy as np
geo_df = geo_df.replace(np.nan, '', regex=True)
geo_df

                 street address     city zip code state
0            9311 BELLA PINE CT  HOUSTON    77078    TX
1               8701 GUSTINE LN  HOUSTON    77031    TX
2                  8064 LENORE   HOUSTON    77017    TX
3              5930 DASHWOOD DR  HOUSTON    77081    TX
4             5218 KENILWOOD DR  HOUSTON    77033    TX
...                         ...      ...      ...   ...
86909  16501 CENTRAL GREEN BLVD  HOUSTON    77032    TX
86910    7815 WILLOW CHASE BLVD  HOUSTON    77070    TX
86911          9550 ELLA LEE LN  HOUSTON    77063    TX
86912           10000 FANNIN ST  HOUSTON    77045    TX
86913             10421 CLAY RD  HOUSTON    77041    TX

[86914 rows x 4 columns]

In [13]:
geo_df[:10].to_csv('2020crimes_first.csv', header=False)

In [16]:
import censusgeocode as cg

k = cg.addressbatch('2020crimes_first.csv')

# Bonus
# Get clean output in Dataframe

df = pd.DataFrame(k, columns=k[0].keys())

In [17]:
k

[OrderedDict([('id', '0'),
              ('address', '9311 BELLA PINE CT, HOUSTON, 77078, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '1'),
              ('address', '8701 GUSTINE LN, HOUSTON, 77031, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '2'),
              ('address', '8064 LENORE , HOUSTON, 77017, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '3'),
              ('address', '5930 DASHWOOD DR, HOUSTON, 77081, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '4'),
              ('address', '5218 KENILWOOD DR, HOUSTON, 77033, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '5'),
              ('address', '2851 WALLINGFORD DR, HOUSTON, 77042, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '6'),
              ('address', '16410 SKEET CT, HOUSTON, 77489, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '7'),
              ('address', '400 80TH ST, HOUSTON, 77012, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '8'),
              ('address', '2434 LIDSTONE , HOUSTON, 77023, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)]),
 OrderedDict([('id', '9'),
              ('address', '8115 PENROD , HOUSTON, 77028, TX'),
              ('match', False),
              ('matchtype', None),
              ('parsed', None),
              ('tigerlineid', None),
              ('side', None),
              ('statefp', None),
              ('countyfp', None),
              ('tract', None),
              ('block', None),
              ('lat', None),
              ('lon', None)])]